# Generated by Django 4.2.2 on 2023-07-01 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_movie_imdb_rating_movie_premiere_movie_pub_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('genre', models.IntegerField(choices=[(2, 'Sci-Fi'), (1, 'Horror'), (3, 'Drama'), (4, 'Comedy'), (0, 'Unknown')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='extra_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_api.extrainfo'),
        ),
    ]
