# Generated by Django 4.2.2 on 2023-07-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_extrainfo_movie_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Unknown'), (4, 'Comedy'), (3, 'Drama'), (2, 'Sci-Fi'), (1, 'Horror')], default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', max_length=256)),
                ('stars', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.movie')),
            ],
        ),
    ]
